# Generated by Django 5.0.2 on 2024-02-27 16:42

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("filme", "0003_rename_descricao_filme_descric"),
    ]

    operations = [
        migrations.RenameField(
            model_name="filme",
            old_name="descric",
            new_name="descricao",
        ),
    ]
